### ISSUE TITLE
Tracking library (prolonged) usage

### ISSUE THREAD

**Issue by btseytlin** [mindsdb/mindsdb_native#33] opened 2020-07-02 08:33 UTC
When mindsdb_native is imported we do an HTTP request to see if any updates are available. 

These requests could be used to anonymously measure how people are using the library. The most interesting thing is Day-X Retention (users in cohort using the library after X days  / total users in cohort): measuring the number of people who continue to use the library after 1 day, 7 days, 30 days, etc. This is a good proxy measure for understanding how useful the library is: the higher the retention, the more people continue using the library.

It can be used to measure the usefulness of a release: if we notice a drop in user retention after some major change then there probably is a problem with the release.

To do this we need to:
* Find out if we can identify prolonged usage from our HTTP logs at all
* If we can, somehow aggregate the metrics and integrate them with MixPanel or something else to display the metric

**Comment by George3d6** [comment] 2020-07-06 02:28
@btseytlin this is a very good idea

Which is why we already do this and have been doing so for ~1 year now :P 

We create a uuid for the installation (random number, fully anonymized) and send it together with the HTTP request for checking the version.

I feel semi-comfortable about it, I mean, it's anonymous, it doesn't take literally any data from the user's computer other than the mindsdb version, so I certainly want to keep it in there for 2.0 as it helps us understand usage patterns.

*However*, as it stands, the check if actually not working as intended, it check the `mindsdb` version and compares it with the `mindsdb_native` version. Can you make it check one or the other (doesn't really matter, both should be up to date) and also make sure that the UUID logic still works with all bathing changes. @btseytlin that is.

**Comment by maximlopin** [comment] 2020-07-06 11:19
**This must be optional and turned off by default**:
We can extend this to tracking column datatypes (and maybe simple stats like `mean`) and prediction accuracies for those datatypes, so we can see where mindsdb performs better and what we should improve.

**Comment by btseytlin** [comment] 2020-07-06 11:25
@George3d6 this issue is more about using the HTTP requests we send for display on dashboards and whatnot and using it to make decisions about the product development path

**Comment by btseytlin** [comment] 2020-07-06 11:26
Made a separate bug issue about the broken update check: https://github.com/mindsdb/mindsdb_native/issues/42

**Comment by George3d6** [comment] 2020-07-06 12:36
Closing.

**Comment by George3d6** [comment] 2020-07-06 12:37
Actually, nvm, this could be a place to discuss prolonged tracking, so reopening it.

**Comment by George3d6** [comment] 2020-07-06 12:38
@torrmal ideas on how/if you want this done?

The way I see it prolonged tracking as a default is a no go.

But if we make it optional, nobody will care to enable it.

**Comment by btseytlin** [comment] 2020-07-06 13:10
@George3d6 lets not confuse tracking individual features and tracking anonymous prolonged usage.

I am not discussing the first one now (tracking column datatypes and whatever), even though it would be great to have. But it is really complicated.

I am only talking about using the data that we already collect - the requests for updates. Just have a plot that shows how many people use the library twice. This one is completely anonymous and no personal data dependency here, no "tracking" really.

**Comment by George3d6** [comment] 2020-07-07 07:52
Ah I see, but @btseytlin since we already stored the UUID we can already do that.

There is nothing that needs to be implemented mindsdb side here, correct ? It's just about how we look at the usage data afterwards.

**Comment by btseytlin** [comment] 2020-07-07 15:06
It seems so! Though it would be useful to have a datetime column on the telemetry server side, so that we can track changes in time

**Comment by btseytlin** [comment] 2020-07-09 13:44
Ok, turned out that sending this data to mixpanel is very easy.
https://developer.mixpanel.com/docs/python

We just have to add a few lines to the telemetry server:
```
from mixpanel import Mixpanel

mp = Mixpanel(PROJECT_TOKEN)

mp.track(uid, 'Update check, {
    'product: 'mindsdb-native',
    'version': '',
    ...
})
``` 

I will do it after we merge this PR and redeploy the telemetry server:
https://github.com/mindsdb/mindsdb_server_enterprise/pull/2

**Comment by btseytlin** [comment] 2020-07-09 14:23
@alejandrovillegas mentioned some important things:
* We need environments. I think its best provided by the client as a query parameter at this point
* The logging should be separated in a separate code block. I think this will be more of an issue if we make more than one route here

**Closed as completed** 2020-09-29 16:30 UTC
Labels: discussion
