### ISSUE TITLE
Very long learning for multiple-target prediction

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#290] opened 2020-11-10 14:19 UTC
Used last staging of mindsdb/native/lightwood.
Dont have gpu.

I train predictor based on 'hdi' dataset. It contains only 225 rows of data. Train without any options take too much time:
```
from time import time
from mindsdb_native import FileDS, Predictor
ds = FileDS('hdi/data.csv')
p = Predictor(name='hdi_test1')

a = time()
p.learn(from_data=ds, to_predict=['GDP ($ per capita)'])
print(time() - a)   # 222.854150056839

a = time()
p.learn(from_data=ds, to_predict=['Pop. Density ', 'GDP ($ per capita)'])
print(time() - a)   # 1297.3500185012817
```

I think 22 mins for small dataset is too much. If it is ok - then please close issue.

**Comment by StpMax** [comment] 2020-11-13 14:50
This is issue for any multiple-target predictions. I tried make predictor from 'concrete_strength' (over 1000 rows) with 2 prediction columns, and stoped learning after 50mins without result.

**Comment by George3d6** [comment] 2020-11-18 14:13
@paxcema any ideas if nonconformist could be causing this ?
Or @maximlopin maybe it's something regrading the mixer selection logic ?

**Comment by paxcema** [comment] 2020-11-26 19:04
Seems to be caused by  Lightwood's `QuantileLoss` (see this somewhat related [issue](https://github.com/mindsdb/lightwood/issues/320)), because resorting to `MSELoss()` makes the issue dissapear.

**Comment by maximlopin** [comment] 2020-12-08 12:15
closed by https://github.com/mindsdb/lightwood/pull/331

**Closed as completed by maximlopin** 2020-12-08 12:15 UTC
Labels: bug, enhancement
